version: '3.9'
services:
  back:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: fastapi_task
    ports:
      - "8000:8000"
    volumes:
      - ./api:/task
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: mysql:8.0
    container_name: fastapi_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: